### ISSUE TITLE
HMI files

### ISSUE THREAD

**Issue by maukcc** [iworld4us/nextion-2.4#2]
Can you add the HMI files for the 2.4 and 2.8 and 3.2 displays?
Much appreciated !

**Comment by iworld4us** [comment]
https://github.com/iworld4us/nextion-2.4

**Comment by maukcc** [comment]
Thank you for your response.
We can see the .tft files, but not the .HMI editor files

**Comment by iworld4us** [comment]
Duplicate of #1.
