### ISSUE TITLE
HMI files

### ISSUE THREAD

**Issue by ThyMollusk** [iworld4us/nextion-2.4#3]
Is it possible to get the HMI file for 3.2 basic? I'd like to make some modifications to suit my printer. Thanks!

**Comment by cekaa** [comment]
Is it possible to get the HMI file for 3.2 enhanced ?????????  I don't know how to install tft file in 3.2 nextion enhanced hmi 
 lcd litle english thanks

**Comment by cekaa** [comment]
I don't know how to install tft file ?????? Is it possible to get the HMI file for 3.2 enhanced hmi lcd thanks

**Comment by iworld4us** [comment]
https://github.com/iworld4us/nextion-2.4/blob/master/mk4duo_3_2_enhanced_436.tft

**Comment by jaymcd** [comment]
I need to change the baud rate in the hmi file. Any chance I can get one for the 3.2" Enhanced screen?

**Comment by iworld4us** [comment]
HMI file added
